[etl]
localhost ansible_connection=local ansible_become_pass='{{ become_password }}'

#[database]
#localhost ansible_connection=local ansible_become_pass='{{ become_password }}'

[development:children]
etl
#database
